python: Remove Python 2.x from CI (#135)
Building with Python 2.x fails in CI due to deprecations

https://github.com/cucumber/gherkin/actions/runs/5545057411/jobs/10162291692?pr=134

```

Run actions/setup-python@v4
Installed versions
  Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
  Version 2.x was not found in the local cache
  Error: The version '2.x' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```